name: Build and Deploy Plugins

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build plugins
        run: npm run build:plugins

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugins-dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Clean gh-pages branch
        run: |
          git rm -rf .
          git clean -fxd

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: plugins-dist
          path: ./dist

      - name: Copy plugins to gh-pages
        run: |
          mkdir -p plugins
          cp -r dist/* plugins/

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add plugins
          git commit -m "Deploy latest plugins build" || echo "No changes to commit"
          git push origin gh-pages
